version: '3.8'

services:
  # Telegram бот
  marketingbot:
    build: .
    container_name: marketingbot
    restart: unless-stopped
    environment:
      # Переменные окружения из .env файла
      - TELEGRAM_BOT_TOKEN=${TELEGRAM_BOT_TOKEN}
      - WEBAPP_URL=${WEBAPP_URL}
      - SHEET_ID=${SHEET_ID:-}
      - SHEET_NAME=${SHEET_NAME:-Sheet1}
      - GCP_SA_JSON=${GCP_SA_JSON:-}
      - GCP_SA_FILE=${GCP_SA_FILE:-}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    volumes:
      # Монтируем .env файл для конфигурации
      - ./.env:/app/.env:ro
      # Опционально: монтируем service account файл
      - ${GCP_SA_FILE:-/dev/null}:${GCP_SA_FILE:-/dev/null}:ro
    # Нет портов - бот работает через Telegram API
    healthcheck:
      test: ["CMD", "pgrep", "-f", "python.*bot.py"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  # Веб-сервер для статических файлов WebApp
  webapp:
    build: .
    container_name: marketingbot-webapp
    restart: unless-stopped
    command: python server.py
    environment:
      - PORT=${WEBAPP_PORT:-8080}
    ports:
      - "${WEBAPP_PORT:-8080}:${WEBAPP_PORT:-8080}"
    volumes:
      - ./webapp:/app/webapp:ro
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${WEBAPP_PORT:-8080}/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
