name: Build and Deploy to Cloud Run

on:
  push:
    branches: [ main, safe/push-sheets-clean ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_JSON }}

      - name: Install gcloud
        run: |
          sudo apt-get update && sudo apt-get install -y google-cloud-sdk docker.io

      - name: Configure Docker for GCR
        run: |
          gcloud auth configure-docker --quiet

      - name: Build and push image to GCR
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
        run: |
          IMAGE=gcr.io/$PROJECT_ID/marketing:${{ github.sha }}
          docker build -t $IMAGE .
          docker push $IMAGE

      - name: Deploy to Cloud Run
        env:
          PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
          REGION: ${{ secrets.GCP_REGION }}
        run: |
          IMAGE=gcr.io/$PROJECT_ID/marketing:${{ github.sha }}
          gcloud run deploy ${{ secrets.CLOUD_RUN_SERVICE_NAME }} --image $IMAGE --region $REGION --platform managed --allow-unauthenticated --quiet
