name: E2E Smoke Test

on:
  workflow_dispatch:
    inputs:
      url:
        description: 'Optional override URL for the auth endpoint (default: http://127.0.0.1:8000/api/webapp/auth)'
        required: false

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Write GCP SA JSON to file
        if: ${{ secrets.GCP_SA_JSON != '' }}
        run: |
          echo "${{ secrets.GCP_SA_JSON }}" > sa.json
          ls -l sa.json

      - name: Start server (uvicorn)
        run: |
          nohup uvicorn app.main:app --host 127.0.0.1 --port 8000 &
          sleep 2

      - name: Run smoke script
        env:
          BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          SHEET_ID: ${{ secrets.SHEET_ID }}
          GCP_SA_FILE: ${{ github.workspace }}/sa.json
        run: |
          URL=${{ github.event.inputs.url || 'http://127.0.0.1:8000/api/webapp/auth' }}
          echo "Running smoke against $URL"
          python scripts/smoke_auth_local.py --partner-code 111098 --phone "+7 982 770-1055" --user-id ${{ secrets.SMOKE_USER_ID }} --url "$URL"
